### ISSUE TITLE
Freeze on STARTING

### ISSUE THREAD

**Issue by iPublicis** [timakro/superfsmon#1]
The surpervisord seems to not being able to restart the program when changes are made.

 /etc/supervisord.d/superfsmon.conf
> [program:superfsmon]
> command=superfsmon -f -d /home/myuser/websites/theapp theapp
> autostart=true
> autorestart=true

 /etc/supervisord.d/theapp.conf
> [program:theapp]
> command=node /home/myuser/websites/theapp/public_html/server.js
> autostart=true
> autorestart=true
> environment=NODE_ENV=production
> stderr_logfile=/home/myuser/websites/theapp/logs/theapp.err.log
> stdout_logfile=/home/mysuer/websites/theapp/logs/theapp.out.log
> user=myuser

When I make changes on the app the supervisord status is as follows:

> [root@myserver /]# supervisorctl status
> superfsmon                       RUNNING   pid 7412, uptime 0:08:05
> wasteapp                          STARTING

It only changes when I do the following:
> [root@myserver /]# supervisorctl reload
> Restarted supervisord
> [root@myserver /]# supervisorctl status
> superfsmon                       RUNNING   pid 7480, uptime 0:00:01
> wasteapp                          RUNNING   pid 7481, uptime 0:00:01

What could be wrong?

Supervisord is the last version. CentOS is version 7.6

**Comment by timakro** [comment]
There is a typo and the path run by nodejs does not match the path monitored by superfsmon (`/wtheapp/` and `/theapp/`). Could that be the problem?

Otherwise it looks like this should work.

**Comment by timakro** [comment]
Looking at your issue again that doesn't seem to be the problem. You could test if this is a nodejs specific issue by replacing the node command with a simple sleep command.

**Comment by iPublicis** [comment]
> 
> 
> There is a typo and the path run by nodejs does not match the path monitored by superfsmon (`/wtheapp/` and `/theapp/`). Could that be the problem?
> 
> Otherwise it looks like this should work.

It was a typo when passing it to here. The right one is `/theapp/`. The issue is not that.

**Comment by iPublicis** [comment]
> 
> 
> There is a typo and the path run by nodejs does not match the path monitored by superfsmon (`/wtheapp/` and `/theapp/`). Could that be the problem?
> 
> Otherwise it looks like this should work.



> 
> 
> Looking at your issue again that doesn't seem to be the problem. You could test if this is a nodejs specific issue by replacing the node command with a simple sleep command.

Will try to check this again. The app is working now with Systemd but I like more Supervisord for this kind of stuff.
